# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'F_Trader_4.ui'
##
## Created by: Qt User Interface Compiler version 6.11.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QHeaderView,
    QLCDNumber, QLabel, QListView, QMainWindow,
    QMenu, QMenuBar, QProgressBar, QPushButton,
    QSizePolicy, QStatusBar, QTableWidget, QTableWidgetItem,
    QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1885, 961)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.P_MercadoEuropeo = QProgressBar(self.centralwidget)
        self.P_MercadoEuropeo.setObjectName(u"P_MercadoEuropeo")
        self.P_MercadoEuropeo.setGeometry(QRect(10, 30, 1281, 25))
        font = QFont()
        font.setPointSize(10)
        self.P_MercadoEuropeo.setFont(font)
        self.P_MercadoEuropeo.setValue(0)
        self.P_MercadoAmericano = QProgressBar(self.centralwidget)
        self.P_MercadoAmericano.setObjectName(u"P_MercadoAmericano")
        self.P_MercadoAmericano.setGeometry(QRect(580, 80, 1281, 25))
        self.P_MercadoAmericano.setFont(font)
        self.P_MercadoAmericano.setStyleSheet(u"QProgressBar::chunk {\n"
"    background-color: orange;\n"
"}")
        self.P_MercadoAmericano.setValue(0)
        self.B_Reiniciar = QPushButton(self.centralwidget)
        self.B_Reiniciar.setObjectName(u"B_Reiniciar")
        self.B_Reiniciar.setGeometry(QRect(1040, 860, 150, 35))
        self.B_Reiniciar.setFont(font)
        self.B_LimpiarResultados = QPushButton(self.centralwidget)
        self.B_LimpiarResultados.setObjectName(u"B_LimpiarResultados")
        self.B_LimpiarResultados.setGeometry(QRect(1220, 860, 100, 35))
        self.B_LimpiarResultados.setFont(font)
        self.B_Cancelar = QPushButton(self.centralwidget)
        self.B_Cancelar.setObjectName(u"B_Cancelar")
        self.B_Cancelar.setGeometry(QRect(1370, 860, 100, 35))
        self.B_Cancelar.setFont(font)
        self.B_Salir = QPushButton(self.centralwidget)
        self.B_Salir.setObjectName(u"B_Salir")
        self.B_Salir.setGeometry(QRect(1520, 860, 100, 35))
        self.B_Salir.setFont(font)
        self.G_Ticker = QGroupBox(self.centralwidget)
        self.G_Ticker.setObjectName(u"G_Ticker")
        self.G_Ticker.setGeometry(QRect(20, 335, 250, 80))
        self.G_Ticker.setFont(font)
        self.B_Ticker = QPushButton(self.G_Ticker)
        self.B_Ticker.setObjectName(u"B_Ticker")
        self.B_Ticker.setGeometry(QRect(148, 33, 82, 34))
        self.B_Ticker.setFont(font)
        self.E_Ticker = QTextEdit(self.G_Ticker)
        self.E_Ticker.setObjectName(u"E_Ticker")
        self.E_Ticker.setGeometry(QRect(20, 33, 111, 31))
        self.G_Lista = QGroupBox(self.centralwidget)
        self.G_Lista.setObjectName(u"G_Lista")
        self.G_Lista.setGeometry(QRect(20, 115, 540, 201))
        self.G_Lista.setFont(font)
        self.E_Lista = QListView(self.G_Lista)
        self.E_Lista.setObjectName(u"E_Lista")
        self.E_Lista.setGeometry(QRect(90, 30, 430, 156))
        self.B_Lista = QPushButton(self.G_Lista)
        self.B_Lista.setObjectName(u"B_Lista")
        self.B_Lista.setGeometry(QRect(10, 30, 31, 31))
        self.B_Lista.setFont(font)
        self.B_Carpeta = QPushButton(self.G_Lista)
        self.B_Carpeta.setObjectName(u"B_Carpeta")
        self.B_Carpeta.setGeometry(QRect(50, 30, 31, 31))
        self.B_Carpeta.setFont(font)
        self.G_Analisis = QGroupBox(self.centralwidget)
        self.G_Analisis.setObjectName(u"G_Analisis")
        self.G_Analisis.setGeometry(QRect(20, 435, 540, 405))
        self.G_Analisis.setFont(font)
        self.E_Visor = QListView(self.G_Analisis)
        self.E_Visor.setObjectName(u"E_Visor")
        self.E_Visor.setGeometry(QRect(10, 30, 520, 365))
        self.G_Resultados = QGroupBox(self.centralwidget)
        self.G_Resultados.setObjectName(u"G_Resultados")
        self.G_Resultados.setGeometry(QRect(580, 115, 1291, 725))
        self.G_Resultados.setFont(font)
        self.E_Resultados = QTableWidget(self.G_Resultados)
        if (self.E_Resultados.columnCount() < 9):
            self.E_Resultados.setColumnCount(9)
        __qtablewidgetitem = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(6, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(7, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.E_Resultados.setHorizontalHeaderItem(8, __qtablewidgetitem8)
        self.E_Resultados.setObjectName(u"E_Resultados")
        self.E_Resultados.setGeometry(QRect(10, 30, 1271, 675))
        self.G_Tiempo = QGroupBox(self.centralwidget)
        self.G_Tiempo.setObjectName(u"G_Tiempo")
        self.G_Tiempo.setGeometry(QRect(290, 335, 270, 80))
        self.C_Tiempo = QCheckBox(self.G_Tiempo)
        self.C_Tiempo.setObjectName(u"C_Tiempo")
        self.C_Tiempo.setGeometry(QRect(20, 38, 21, 21))
        self.E_Tiempo = QTextEdit(self.G_Tiempo)
        self.E_Tiempo.setObjectName(u"E_Tiempo")
        self.E_Tiempo.setGeometry(QRect(50, 33, 61, 31))
        self.L_Tiempo = QLabel(self.G_Tiempo)
        self.L_Tiempo.setObjectName(u"L_Tiempo")
        self.L_Tiempo.setGeometry(QRect(120, 38, 65, 18))
        font1 = QFont()
        font1.setPointSize(12)
        self.L_Tiempo.setFont(font1)
        self.lcd_Loop = QLCDNumber(self.G_Tiempo)
        self.lcd_Loop.setObjectName(u"lcd_Loop")
        self.lcd_Loop.setGeometry(QRect(188, 30, 72, 35))
        self.lcd_Loop.setDigitCount(8)
        self.lcd_Reloj = QLCDNumber(self.centralwidget)
        self.lcd_Reloj.setObjectName(u"lcd_Reloj")
        self.lcd_Reloj.setGeometry(QRect(1700, 0, 161, 51))
        self.lcd_Reloj.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1130, 60, 161, 18))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(470, 10, 141, 25))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 5, 58, 25))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(950, 10, 41, 25))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(520, 60, 40, 20))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1820, 60, 41, 16))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1885, 30))
        self.menuOpciones = QMenu(self.menubar)
        self.menuOpciones.setObjectName(u"menuOpciones")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuOpciones.menuAction())

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Mi Screener V5.7    09/10/2026", None))
        self.P_MercadoEuropeo.setFormat("")
        self.P_MercadoAmericano.setFormat("")
        self.B_Reiniciar.setText(QCoreApplication.translate("MainWindow", u"Reiniciar an\u00e1lisis", None))
        self.B_LimpiarResultados.setText(QCoreApplication.translate("MainWindow", u"Limpiar", None))
        self.B_Cancelar.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.B_Salir.setText(QCoreApplication.translate("MainWindow", u"Salir", None))
        self.G_Ticker.setTitle(QCoreApplication.translate("MainWindow", u"TICKER", None))
        self.B_Ticker.setText(QCoreApplication.translate("MainWindow", u"Analizar", None))
        self.G_Lista.setTitle(QCoreApplication.translate("MainWindow", u"LISTA", None))
        self.B_Lista.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.B_Carpeta.setText(QCoreApplication.translate("MainWindow", u"Dir", None))
        self.G_Analisis.setTitle(QCoreApplication.translate("MainWindow", u"ANALISIS ", None))
        self.G_Resultados.setTitle(QCoreApplication.translate("MainWindow", u"RESULTADOS", None))
        ___qtablewidgetitem = self.E_Resultados.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Ticker", None))
        ___qtablewidgetitem1 = self.E_Resultados.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Se\u00f1al", None))
        ___qtablewidgetitem2 = self.E_Resultados.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Tendencia", None))
        ___qtablewidgetitem3 = self.E_Resultados.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"CFI Diario", None))
        ___qtablewidgetitem4 = self.E_Resultados.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"CFI Semanal", None))
        ___qtablewidgetitem5 = self.E_Resultados.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Flow", None))
        ___qtablewidgetitem6 = self.E_Resultados.horizontalHeaderItem(6)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"Smart Money", None))
        ___qtablewidgetitem7 = self.E_Resultados.horizontalHeaderItem(7)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"Vol.Relativo", None))
        ___qtablewidgetitem8 = self.E_Resultados.horizontalHeaderItem(8)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"Fecha", None))
        self.G_Tiempo.setTitle(QCoreApplication.translate("MainWindow", u"LOOP", None))
        self.C_Tiempo.setText("")
        self.L_Tiempo.setText(QCoreApplication.translate("MainWindow", u"Minutos", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"MERCADO AMERICANO", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"MERCADO EUROPEO", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"09:30", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"17:00", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"15:30", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"22:00", None))
        self.menuOpciones.setTitle(QCoreApplication.translate("MainWindow", u"Opciones", None))
    # retranslateUi

