# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/run/media/jac4806/Mis Cosas/Proyectos/Trader/F_Trader_3.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_F_Trader(object):
    def setupUi(self, F_Trader):
        F_Trader.setObjectName("F_Trader")
        F_Trader.resize(750, 621)
        self.B_Cargar = QtWidgets.QPushButton(F_Trader)
        self.B_Cargar.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.B_Cargar.setObjectName("B_Cargar")
        self.L_Lista = QtWidgets.QListView(F_Trader)
        self.L_Lista.setGeometry(QtCore.QRect(50, 40, 431, 31))
        self.L_Lista.setObjectName("L_Lista")
        self.B_Cancelar = QtWidgets.QPushButton(F_Trader)
        self.B_Cancelar.setGeometry(QtCore.QRect(530, 570, 88, 34))
        self.B_Cancelar.setObjectName("B_Cancelar")
        self.B_Salir = QtWidgets.QPushButton(F_Trader)
        self.B_Salir.setGeometry(QtCore.QRect(650, 570, 88, 34))
        self.B_Salir.setObjectName("B_Salir")
        self.T_Resultados = QtWidgets.QTableWidget(F_Trader)
        self.T_Resultados.setGeometry(QtCore.QRect(10, 210, 731, 351))
        self.T_Resultados.setObjectName("T_Resultados")
        self.T_Resultados.setColumnCount(0)
        self.T_Resultados.setRowCount(0)
        self.L_Visor = QtWidgets.QListView(F_Trader)
        self.L_Visor.setGeometry(QtCore.QRect(10, 90, 731, 101))
        self.L_Visor.setObjectName("L_Visor")
        self.B_Analizar = QtWidgets.QPushButton(F_Trader)
        self.B_Analizar.setGeometry(QtCore.QRect(510, 40, 88, 34))
        self.B_Analizar.setObjectName("B_Analizar")

        self.retranslateUi(F_Trader)
        QtCore.QMetaObject.connectSlotsByName(F_Trader)

    def retranslateUi(self, F_Trader):
        _translate = QtCore.QCoreApplication.translate
        F_Trader.setWindowTitle(_translate("F_Trader", "Dialog"))
        self.B_Cargar.setText(_translate("F_Trader", "..."))
        self.B_Cancelar.setText(_translate("F_Trader", "Cancelar"))
        self.B_Salir.setText(_translate("F_Trader", "Salir"))
        self.B_Analizar.setText(_translate("F_Trader", "Analizar"))
